# Generated by Django 4.0.3 on 2022-03-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_client_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='client',
            new_name='customer',
        ),
    ]
