# Generated by Django 4.0.3 on 2022-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_rename_client_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания (отправки)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=20, verbose_name='статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
